apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.allow-http: "false"
  generation: 1
  name: crapi-web-ingress
  namespace: crapi
spec:
  ingressClassName: nginx
  rules:
  - host: crapi.staging.k8s.guardrails.io
    http:
      paths:
      - backend:
          service:
            name: crapi-web 
            port:
              number: 80
        path: /
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - crapi.staging.k8s.guardrails.io
    secretName: crapi.staging.k8s.guardrails.io